name: JFrog Xray Scan envir

on: [push]

env:
  XRAY_SERVER_URL: ${{ secrets.XRAY_SERVER_URL }}
  XRAY_USERNAME: ${{ secrets.XRAY_USERNAME }}
  XRAY_PASSWORD: ${{ secrets.XRAY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Variable
      run: |
        echo "The value of MY_VAR is '${{ secrets.XRAY_SERVER_URL }}'"
        
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install JFrog CLI
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/


    - name: Scan with JFrog Xray
      run: |
        jfrog xr c --url="${XRAY_SERVER_URL}" --user="${XRAY_USERNAME}" --password="${XRAY_PASSWORD}"
        jfrog xr maven --fail=true target/*.jar
